rem -------------------------------------
ObjectTemplate.create Kit flak18_deployer_kit
ObjectTemplate.addTemplate heer_knife
ObjectTemplate.addTemplate waltherP38-i3
ObjectTemplate.addTemplate flak18_dep
ObjectTemplate.addTemplate dressing_de
include fht_deployer_kits.tweak
rem -------------------------------------
rem -------------------------------------
ObjectTemplate.create Kit flak18ns_deployer_kit
ObjectTemplate.addTemplate heer_knife
ObjectTemplate.addTemplate waltherP38-i3
ObjectTemplate.addTemplate flak18ns_dep
ObjectTemplate.addTemplate dressing_de
include fht_deployer_kits.tweak
rem -------------------------------------
rem -------------------------------------
ObjectTemplate.create Kit flak37_deployer_kit
ObjectTemplate.addTemplate heer_knife
ObjectTemplate.addTemplate waltherP38-i3
ObjectTemplate.addTemplate flak37_dep
ObjectTemplate.addTemplate dressing_de
include fht_deployer_kits.tweak
rem -------------------------------------
rem -------------------------------------
ObjectTemplate.create Kit flak38_deployer_kit
ObjectTemplate.addTemplate heer_knife
ObjectTemplate.addTemplate waltherP38-i3
ObjectTemplate.addTemplate flak38_dep
ObjectTemplate.addTemplate dressing_de
include fht_deployer_kits.tweak
rem -------------------------------------
rem -------------------------------------
ObjectTemplate.create Kit flak43_deployer_kit
ObjectTemplate.addTemplate heer_knife
ObjectTemplate.addTemplate waltherP38-i3
ObjectTemplate.addTemplate flak43_dep
ObjectTemplate.addTemplate dressing_de
include fht_deployer_kits.tweak
rem -------------------------------------
rem -------------------------------------
ObjectTemplate.create Kit flakvierling_deployer_kit
ObjectTemplate.addTemplate heer_knife
ObjectTemplate.addTemplate waltherP38-i3
ObjectTemplate.addTemplate flakvierling_dep
ObjectTemplate.addTemplate dressing_de
include fht_deployer_kits.tweak
rem -------------------------------------
rem -------------------------------------
ObjectTemplate.create Kit kwk5cm_deployer_kit
ObjectTemplate.addTemplate heer_knife
ObjectTemplate.addTemplate waltherP38-i3
ObjectTemplate.addTemplate kwk5cm_dep
ObjectTemplate.addTemplate dressing_de
include fht_deployer_kits.tweak
rem -------------------------------------
rem -------------------------------------
ObjectTemplate.create Kit lefh18_deployer_kit
ObjectTemplate.addTemplate heer_knife
ObjectTemplate.addTemplate waltherP38-i3
ObjectTemplate.addTemplate lefh18_dep
ObjectTemplate.addTemplate dressing_de
include fht_deployer_kits.tweak
rem -------------------------------------
rem -------------------------------------
ObjectTemplate.create Kit nebelwerfer_deployer_kit
ObjectTemplate.addTemplate heer_knife
ObjectTemplate.addTemplate waltherP38-i3
ObjectTemplate.addTemplate nebelwerfer_dep
ObjectTemplate.addTemplate dressing_de
include fht_deployer_kits.tweak
rem -------------------------------------
rem -------------------------------------
ObjectTemplate.create Kit pak35_deployer_kit
ObjectTemplate.addTemplate heer_knife
ObjectTemplate.addTemplate waltherP38-i3
ObjectTemplate.addTemplate pak35_dep
ObjectTemplate.addTemplate dressing_de
include fht_deployer_kits.tweak
rem -------------------------------------
rem -------------------------------------
ObjectTemplate.create Kit pak38_deployer_kit
ObjectTemplate.addTemplate heer_knife
ObjectTemplate.addTemplate waltherP38-i3
ObjectTemplate.addTemplate pak38_dep
ObjectTemplate.addTemplate dressing_de
include fht_deployer_kits.tweak
rem -------------------------------------
rem -------------------------------------
ObjectTemplate.create Kit pak40_deployer_kit
ObjectTemplate.addTemplate heer_knife
ObjectTemplate.addTemplate waltherP38-i3
ObjectTemplate.addTemplate pak40_dep
ObjectTemplate.addTemplate dressing_de
include fht_deployer_kits.tweak
rem -------------------------------------
rem -------------------------------------
ObjectTemplate.create Kit sig33_deployer_kit
ObjectTemplate.addTemplate heer_knife
ObjectTemplate.addTemplate waltherP38-i3
ObjectTemplate.addTemplate sig33_dep
ObjectTemplate.addTemplate dressing_de
include fht_deployer_kits.tweak
rem -------------------------------------
rem -------------------------------------
ObjectTemplate.create Kit wurfgerat_deployer_kit
ObjectTemplate.addTemplate heer_knife
ObjectTemplate.addTemplate waltherP38-i3
ObjectTemplate.addTemplate wurfgerat_dep
ObjectTemplate.addTemplate dressing_de
include fht_deployer_kits.tweak
rem -------------------------------------
rem -------------------------------------
ObjectTemplate.create Kit 2pdr_deployer_kit
ObjectTemplate.addTemplate Sykes_knife
ObjectTemplate.addTemplate webleymk6-i3
ObjectTemplate.addTemplate 2pdr_dep
ObjectTemplate.addTemplate dressing_gb
include fht_deployer_kits.tweak
rem -------------------------------------
rem -------------------------------------
ObjectTemplate.create Kit 25pdr_deployer_kit
ObjectTemplate.addTemplate Sykes_knife
ObjectTemplate.addTemplate webleymk6-i3
ObjectTemplate.addTemplate 25pdr_dep
ObjectTemplate.addTemplate dressing_gb
include fht_deployer_kits.tweak
rem -------------------------------------
rem -------------------------------------
ObjectTemplate.create Kit 25pdr_mkiv_deployer_kit
ObjectTemplate.addTemplate Sykes_knife
ObjectTemplate.addTemplate webleymk6-i3
ObjectTemplate.addTemplate 25pdr_mkiv_dep
ObjectTemplate.addTemplate dressing_gb
include fht_deployer_kits.tweak
rem -------------------------------------
rem -------------------------------------
ObjectTemplate.create Kit 6pdr_deployer_kit
ObjectTemplate.addTemplate Sykes_knife
ObjectTemplate.addTemplate webleymk6-i3
ObjectTemplate.addTemplate 6pdr_dep
ObjectTemplate.addTemplate dressing_gb
include fht_deployer_kits.tweak
rem -------------------------------------
rem -------------------------------------
ObjectTemplate.create Kit 6pdr_mkiv_deployer_kit
ObjectTemplate.addTemplate Sykes_knife
ObjectTemplate.addTemplate webleymk6-i3
ObjectTemplate.addTemplate 6pdr_mkiv_dep
ObjectTemplate.addTemplate dressing_gb
include fht_deployer_kits.tweak
rem -------------------------------------
rem -------------------------------------
ObjectTemplate.create Kit bofors_deployer_kit
ObjectTemplate.addTemplate Sykes_knife
ObjectTemplate.addTemplate webleymk6-i3
ObjectTemplate.addTemplate bofors_dep
ObjectTemplate.addTemplate dressing_gb
include fht_deployer_kits.tweak
rem -------------------------------------
rem -------------------------------------
ObjectTemplate.create Kit breda35_deployer_kit
ObjectTemplate.addTemplate m39combatknife
ObjectTemplate.addTemplate beretta34-i3
ObjectTemplate.addTemplate breda35_dep
ObjectTemplate.addTemplate dressing_it
include fht_deployer_kits.tweak
rem -------------------------------------
rem -------------------------------------
ObjectTemplate.create Kit cannone47_deployer_kit
ObjectTemplate.addTemplate m39combatknife
ObjectTemplate.addTemplate beretta34-i3
ObjectTemplate.addTemplate cannone47_dep
ObjectTemplate.addTemplate dressing_it
include fht_deployer_kits.tweak
rem -------------------------------------
rem -------------------------------------
ObjectTemplate.create Kit schneider_1913_deployer_kit
ObjectTemplate.addTemplate m39combatknife
ObjectTemplate.addTemplate beretta34-i3
ObjectTemplate.addTemplate schneider_1913_dep
ObjectTemplate.addTemplate dressing_it
include fht_deployer_kits.tweak
rem -------------------------------------
rem -------------------------------------
ObjectTemplate.create Kit 37mm_deployer_kit
ObjectTemplate.addTemplate m3_knife
ObjectTemplate.addTemplate Colt1911-i3
ObjectTemplate.addTemplate 37mm_dep
ObjectTemplate.addTemplate carlisle_dressing
include fht_deployer_kits.tweak
rem -------------------------------------
rem -------------------------------------
ObjectTemplate.create Kit 57mm_deployer_kit
ObjectTemplate.addTemplate m3_knife
ObjectTemplate.addTemplate Colt1911-i3
ObjectTemplate.addTemplate 57mm_dep
ObjectTemplate.addTemplate carlisle_dressing
include fht_deployer_kits.tweak
rem -------------------------------------
rem -------------------------------------
ObjectTemplate.create Kit 76mm_deployer_kit
ObjectTemplate.addTemplate m3_knife
ObjectTemplate.addTemplate Colt1911-i3
ObjectTemplate.addTemplate 76mm_dep
ObjectTemplate.addTemplate carlisle_dressing
include fht_deployer_kits.tweak
rem -------------------------------------
rem -------------------------------------
ObjectTemplate.create Kit 90mm_deployer_kit
ObjectTemplate.addTemplate m3_knife
ObjectTemplate.addTemplate Colt1911-i3
ObjectTemplate.addTemplate 90mm_dep
ObjectTemplate.addTemplate carlisle_dressing
include fht_deployer_kits.tweak
rem -------------------------------------
rem -------------------------------------
ObjectTemplate.create Kit m2a1_deployer_kit
ObjectTemplate.addTemplate m3_knife
ObjectTemplate.addTemplate Colt1911-i3
ObjectTemplate.addTemplate m2a1_dep
ObjectTemplate.addTemplate carlisle_dressing
include fht_deployer_kits.tweak
rem -------------------------------------
rem -------------------------------------
ObjectTemplate.create Kit m33_deployer_kit
ObjectTemplate.addTemplate m3_knife
ObjectTemplate.addTemplate Colt1911-i3
ObjectTemplate.addTemplate m33_dep
ObjectTemplate.addTemplate carlisle_dressing
include fht_deployer_kits.tweak
rem -------------------------------------
rem -------------------------------------
ObjectTemplate.create Kit m51_deployer_kit
ObjectTemplate.addTemplate m3_knife
ObjectTemplate.addTemplate Colt1911-i3
ObjectTemplate.addTemplate m51_dep
ObjectTemplate.addTemplate carlisle_dressing
include fht_deployer_kits.tweak
rem -------------------------------------