rem *** corrects the 30mm frontal armour (was 80mm, should be 50mm) ***

ObjectTemplate.activeSafe PlayerControlObject cromwell
ObjectTemplate.mapMaterial 2 30mmAt25 127

ObjectTemplate.activeSafe PlayerControlObject cromwell_95
ObjectTemplate.mapMaterial 2 30mmAt25 127

ObjectTemplate.activeSafe PlayerControlObject cromwell_irishguard
ObjectTemplate.mapMaterial 2 30mmAt25 127

ObjectTemplate.activeSafe PlayerControlObject cromwell_polish
ObjectTemplate.mapMaterial 2 30mmAt25 127
