ObjectTemplate.activeSafe Engine kubelwagen_win_zMotor
ObjectTemplate.setAcceleration 0/0/12
ObjectTemplate.setTorque 100
ObjectTemplate.setGearDown 0.5
ObjectTemplate.setGearChangeTime 0.5
ObjectTemplate.newCar2.wheelInertia 20
ObjectTemplate.newCar2.engineFeedbackMod 0.3
ObjectTemplate.newCar2.brakeTorque 1500
ObjectTemplate.newCar2.engineBrakeTorque 500
ObjectTemplate.newCar2.frictionMod 1.4
ObjectTemplate.newCar2.slopeTorqueMod 0.95
ObjectTemplate.newCar2.wheelLongScale 0.06

ObjectTemplate.activeSafe Engine kubelwagen_win_alt_zMotor
ObjectTemplate.setAcceleration 0/0/12
ObjectTemplate.setTorque 100
ObjectTemplate.setGearDown 0.5
ObjectTemplate.setGearChangeTime 0.5
ObjectTemplate.newCar2.wheelInertia 20
ObjectTemplate.newCar2.engineFeedbackMod 0.3
ObjectTemplate.newCar2.brakeTorque 1500
ObjectTemplate.newCar2.engineBrakeTorque 500
ObjectTemplate.newCar2.frictionMod 1.4
ObjectTemplate.newCar2.slopeTorqueMod 0.95
ObjectTemplate.newCar2.wheelLongScale 0.06

ObjectTemplate.activeSafe kubelwagen_fr_zMotor
ObjectTemplate.setAcceleration 0/0/12
ObjectTemplate.setTorque 100
ObjectTemplate.setGearDown 0.5
ObjectTemplate.setGearChangeTime 0.5
ObjectTemplate.newCar2.wheelInertia 20
ObjectTemplate.newCar2.engineFeedbackMod 0.3
ObjectTemplate.newCar2.brakeTorque 1500
ObjectTemplate.newCar2.engineBrakeTorque 500
ObjectTemplate.newCar2.frictionMod 1.4
ObjectTemplate.newCar2.slopeTorqueMod 0.95
ObjectTemplate.newCar2.wheelLongScale 0.06

ObjectTemplate.activeSafe kubelwagen_fr_alt_zMotor
ObjectTemplate.setAcceleration 0/0/12
ObjectTemplate.setTorque 100
ObjectTemplate.setGearDown 0.5
ObjectTemplate.setGearChangeTime 0.5
ObjectTemplate.newCar2.wheelInertia 20
ObjectTemplate.newCar2.engineFeedbackMod 0.3
ObjectTemplate.newCar2.brakeTorque 1500
ObjectTemplate.newCar2.engineBrakeTorque 500
ObjectTemplate.newCar2.frictionMod 1.4
ObjectTemplate.newCar2.slopeTorqueMod 0.95
ObjectTemplate.newCar2.wheelLongScale 0.06

ObjectTemplate.activeSafe kubelwagen_zMotor
ObjectTemplate.setAcceleration 0/0/12
ObjectTemplate.setTorque 100
ObjectTemplate.setGearDown 0.5
ObjectTemplate.setGearChangeTime 0.5
ObjectTemplate.newCar2.wheelInertia 20
ObjectTemplate.newCar2.engineFeedbackMod 0.3
ObjectTemplate.newCar2.brakeTorque 1500
ObjectTemplate.newCar2.engineBrakeTorque 500
ObjectTemplate.newCar2.frictionMod 1.4
ObjectTemplate.newCar2.slopeTorqueMod 0.95
ObjectTemplate.newCar2.wheelLongScale 0.06
